PATH=$HOME/bin:$PATH

if [ -f /etc/bash_completion ]; then
   . /etc/bash_completion
fi

function cs () {
	cd "$@" && ls -a
}
alias cl='cs'
alias pj='cd ~/Documents/Projects && ls -d *'
alias ed='subl'
alias host='sudo subl /etc/hosts'
alias server='python -m SimpleHTTPServer'
alias status='git status -sb'
alias git-merge='git merge --no-ff'
alias fetch='git fetch && git branch -v'
alias chrome='/usr/bin/open -a "/Applications/Google Chrome.app"'


# Git commands
alias gs='git status '
alias ga='git add '
alias gb='git branch -v'
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'

alias gm='git mg'
alias mg='gm'

alias got='git '
alias get='git '

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced


function cheat () {
	git push
	git checkout $1

	if [ "$2" = "-d" ]; then
		git fetch origin $(git symbolic-ref --short HEAD)
		git pull
		git merge --no-ff @{-1}		
		git deploy $1
	else
		git merge --no-ff @{-1}
	fi
}

function deploy () {
	git fetch origin $(git symbolic-ref --short HEAD)
	git pull
	git push
	git deploy $1
}


function _update_ps1() {
	export PS1="$(~/powerline-shell.py --cwd-only $? 2> /dev/null)"
}

export PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"

if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi