PATH=$HOME/bin:$PATH

if [ -f /etc/bash_completion ]; then
   . /etc/bash_completion
fi

function cs () {
	cd "$@" && ls -a
}

function project () {
	open ~/Projects/1/$1
}

alias cl='cs'
alias pj='cd ~/Projects && ls -d *'
alias fun='cd ~/Documents/fun && ls -d *'
alias rice='cd ~/rice && ls -d *'
alias vag='vagrant up && gulp'
alias ed='nvim'
# alias host='sudo code /etc/hosts -r --user-data-dir="~/.vscode-root"'
alias host='sudo nvim /etc/hosts'
alias server='python -m SimpleHTTPServer'
alias status='git status -sb'
alias git-merge='git merge --no-ff'
alias fetch='git fetch && git branch -v'
alias chrome='/usr/bin/open -a "/Applications/Google Chrome.app"'
alias npmlist='npm list -g --depth=0'
alias 1='project'
# alias composer='composer.phar'
# alias go='tmux attach -t'
alias dockerip="docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'"
alias webcam-fix='sudo killall AppleCameraAssistant; sudo killall VDCAssistant'
alias docker-purge='docker stop $(docker ps -aq)'

# Git commands
alias gs='git status '
alias ga='git add '
alias gb='git branch -v'
alias gc='git commit'
alias gd='git diff'
alias gk='gitk --all&'
alias gx='gitx --all'
alias sourcetree='open -a SourceTree'

alias gm='git mg'
alias mg='gm'

alias got='git '
alias get='git '

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export FIGNORE=.DS_Store

# export DOCKER_TLS_VERIFY="1"
# export DOCKER_HOST="tcp://192.168.99.100:2376"
# export DOCKER_CERT_PATH="/Users/rdelrio/.docker/machine/machines/default"
# export DOCKER_MACHINE_NAME="default"
# eval $(docker-machine env default)

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib"
export CUDA_HOME=/usr/local/cuda

eval "$(thefuck --alias)"

function cheat () {
	git push
	git checkout $1

	if [ "$2" != "-f"]; then
		git fetch origin $(git symbolic-ref --short HEAD)
		git pull
    fi

    if [ "$2" = "-d" ]; then
		git merge --no-ff @{-1}		
		git deploy $1
	else
		git merge --no-ff @{-1}
	fi
}

function gt () {
	cd ~/Projects
	cd $1
	ls -d *
	if [ "$1" ]; then
		gs
	fi
}

function pane () {
	pwd=$(pwd)
	osascript -e 'tell application "System Events" to key code 2 using {shift down, command down}'
	tell application "iTerm"
		delay 6
		write text "cd $pwd"
	end tell
	osascript -e 'tell application "System Events" to keystroke "[" using {command down}'
	$1
	osascript -e 'tell application "System Events" to keystroke "[" using {command down}'
}

function deploy () {
	git fetch origin $(git symbolic-ref --short HEAD)
	git pull
	git push
	git deploy $1
}

function pullout () {
	git push
	git checkout -
}

function undo () {
	git reset --hard HEAD~1
}

function linestat () {
	arg=$1 || "1 day"
	git log --shortstat --since "$arg ago"|\
	grep "files changed" |\
	awk '{files+=$1; inserted+=$4; deleted+=$6} END {print "Files Changed", files, "Lines Inserted:", inserted, "Lines Deleted:", deleted}'
}

if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi

source "$HOME/.profile"

##
# Your previous /Users/rdelrio/.bash_profile file was backed up as /Users/rdelrio/.bash_profile.macports-saved_2016-07-21_at_18:27:17
##

# MacPorts Installer addition on 2016-07-21_at_18:27:17: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

# test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
# MacPorts Installer addition on 2017-01-06_at_10:26:51: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

eval "$(docker-machine env -u)"
unset DOCKER_TLS_VERIFY
unset DOCKER_HOST
unset DOCKER_CERT_PATH
unset DOCKER_MACHINE_NAME

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Use pyenv instead of homebrew
eval "$(pyenv init -)"
export PATH="$PATH:/Applications/DevDesktop/tools"